### ISSUE TITLE
prompt-toolkit version is pretty old and conflicts...

### ISSUE THREAD

**Issue by arnicas** [Microsoft/TextWorld#107]
Hi, the required version of prompt_toolkit conflicts with Jupyter notebook current install version... is this resolveable? you have notebook examples in here.  thanks.

jupyter-console 6.0.0 has requirement prompt_toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.15 which is incompatible.
ipython 7.2.0 has requirement prompt-toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.15 which is incompatible.

**Comment by MarcCote** [comment]
Thanks for reporting this. We had to pin down `prompt_toolkit`'s version because of conflicting issues with older version of ipython and jupyter-console (see https://github.com/jupyter/jupyter_console/issues/158). Now that it seems resolved, we'll unpin it.

**Comment by arnicas** [comment]
Thanks, it runs just fine with the latest prompt_toolkit and the notebook too :)

**Comment by krispymelody** [comment]
Hi, I am trying to install textworld in Google Colab and importing textworld will trigger this error message:

ContextualVersionConflict: (prompt-toolkit 1.0.16 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('prompt-toolkit<2.1.0,>=2.0.0'), {'textworld'})

I've tried to install multiple version of prompt-toolkit but still did not resolve the issue. Would be appreciated if you could look into it.
