### ISSUE TITLE
Issue with creating a coin collector example

### ISSUE THREAD

**Issue by prabhatnagarajan** [Microsoft/TextWorld#113]
I'm trying to reproduce the Coin Collector example from the paper:
"Counting to Explore and Generalize in Text-based Games" (https://arxiv.org/abs/1806.11525).

However, I'm having some difficulty getting a basic example working
with default options. Consider the following code:

```
import textworld.challenges
import textworld
from pdb import set_trace
game_options = textworld.GameOptions()
textworld.challenges.coin_collector.make_game('simple', game_options)
```

This yields the following error:
```
  File "/home/prabhatn/mud-rl/textworld/challenges/coin_collector.py", line 93, in make_game
    rngs = options.rngs
  File "/home/prabhatn/mud-rl/textworld/generator/game.py", line 1058, in rngs
    for key, seed in self._seeds.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

However, the constructor for GameOptions doesn't take in or require a seeds argument.

Anyhow, this can be rectified by adding the line:

```
game_options.seeds = 5
```
before the final line that creates the game. However, I then get the error:

```
  File "/home/prabhatn/mud-rl/textworld/challenges/coin_collector.py", line 143, in make_game
    M.set_quest_from_commands(walkthrough)
  File "/home/prabhatn/mud-rl/textworld/generator/maker.py", line 586, in set_quest_from_commands
    event = Event(actions=actions, conditions=winning_facts)
  File "/home/prabhatn/mud-rl/textworld/generator/game.py", line 92, in __init__
    self.condition = self.set_conditions(conditions)
  File "/home/prabhatn/mud-rl/textworld/generator/game.py", line 111, in set_conditions
    raise UnderspecifiedEventError()
textworld.generator.game.UnderspecifiedEventError: Either the actions or the conditions is needed to create an event.
```

Further digging suggests that the action space is empty.

Is there any code to reproduce the coin collector example from the paper?

Any help is appreciated.

**Comment by xingdi-eric-yuan** [comment]
Hi @prabhatnagarajan , for now please try using this commit of textworld for running coin collector experiments.
`042bef427cefaac8b87edcb80cf42cd7b0c62d88`
Thanks for pointing this out, we should have made a branch for coin collector environment. We will do this after holiday, and I will mention it in coin collector's README. We will let you know when we're done.

**Comment by xingdi-eric-yuan** [comment]
I have made a new TextWorld branch "coin_collector". I'm closing this comment, please re-open it if you have any problem.
