### ISSUE TITLE
Guide to source code?

### ISSUE THREAD

**Issue by roschler** [Microsoft/TextWorld#115]
Is there a document that gives a guide to the code?  The `src` sub-directory is virtually empty so I'm assuming that actual code that does the heavy lifting is downloaded later?  I'm referring to the code that does things like the actual RL agent training, or more interesting to an NLP programmer like me, the vocabulary+context based sentence generator.  Those are some of the interesting TextWorld components I heard mentioned by David Tao in his YouTube video on TextWorld:

https://www.youtube.com/watch?v=KRXit7rx0N8

Also, is the RL training CUDA based?  I have a Titan X card but it's from the first generation line so it's a bit slow and the drivers are finicky.

**Comment by tavianator** [comment]
You're right, `src` is not where most of the source lives.  You'll find it in the [`textworld`](https://github.com/Microsoft/TextWorld/tree/master/textworld) directory.

There is some documentation that covers the framework here: https://textworld.readthedocs.io/en/latest/.  The notes about text generation are here: https://textworld.readthedocs.io/en/latest/notes/cfg.html.

TextWorld itself doesn't have an RL agent implementation, it's just an environment.  But we have a baseline agent on the competition page at https://competitions.codalab.org/competitions/20865#participate-get_starting_kit.  I believe it does use CUDA at training time, but it should be easily tweakable.

**Comment by roschler** [comment]
@tavianator Thanks!

**Comment by MarcCote** [comment]
I think this can be closed. If you feel otherwise, please re-open it.
