### ISSUE TITLE
Basic theme is broken.

### ISSUE THREAD

**Issue by tshrjn** [Microsoft/TextWorld#143]
Hi there,

Trying to create a game with the `basic` theme instead of the house theme returns with an error in tokenization: 
```
tatsu.exceptions.FailedToken: FailedToken: /path/to/TextWorld/textworld/generator/data/text_grammars/basic_obj.twg(85:35) expecting '|' :
(k<->d)_match:#letter#-#(k)_noun# <-> #letter#-#(d)_noun#
```

This is encountered irrespective of wheather the game is being made from cli like `tw-make custom --theme basic` or via the API call of `textworld.make(options)`.

**Comment by tavianator** [comment]
Thanks for the report!  Should be fixed by #144, let us know if that's not the case.
