### ISSUE TITLE
Simple agent with TextWorld doesn't have any explanation

### ISSUE THREAD

**Issue by mohanr** [microsoft/TextWorld#158]
I believe the agent in the notebook doesn't have any description. Is it possible to include any other material to support the code ? I am not sure if a more simple agent would help to get started. I can try a simpler version if I manage to understand enough.

**Comment by MarcCote** [comment]
Hi @mohanr, thank you for your feedback. We are going to better describe what's going on in the agent example code. Here's a high-level description in case you need it now.

The agent receives as input the concatenation of the description of the room (output of the `look` command), its inventory contents (output of the `inventory` command) and the game's narrative (previous command feedback). A GRU encoder (`encoder_gru`) is used to parse the input text and extract features at the current game step. Those features are then provided as input to another GRU (`state_gru`) that serves as a state history and spans the whole episode.

To select which commands to send to the game, the agent gets the list of all admissible commands (provided by TextWorld) and scores each of them conditioned on the current hidden state of the `state_gru`. To do that, another GRU encoder (`cmd_encoder_gru`) is used to encode each text command separately. Then, a simple linear layer (`att_cmd`) is used to output a score given the concatenation of an encoded command and the current hidden state of the `state_gru`.

Note, that word embedding (`embedding`) is learned from scratch but one could use a pre-trained one like word2vec, GloVe, ELMo or BERT.

The agent is trained using A2C (batch size of 1). The critic shares the same bottom layers as the agent and uses a simple linear layer (`critic`) to output a single scalar value given the current hidden state of the `state_gru`.

The model also uses entropy regularization to promote exploration.

**Comment by gari-marcos** [comment]
Hello, I was reviewing the algorithm and I saw the ```critic``` is calculated the ```state_output``` instead of the ```state_hidden``` as it is shown in the 8th line of the ```forward```function. Could you please tell me if I am wrong?
Thank you in advance.

**Comment by Acejoy** [comment]
Hey, I am new to RL and got interested in its applications in NLP. I was wondering how would one implement LSTM-DQN ([https://arxiv.org/pdf/1506.08941.pdf](url) using textworld. I tried to find all possible actions from the gamefile , but wasn't successful. In OpenAi's GYM , env.action_space gives the action list. Is there any way to get it in textworld?

**Comment by MarcCote** [comment]
Hi @Acejoy, here is a [blog post](https://www.microsoft.com/en-us/research/blog/by-making-text-based-games-more-accessible-to-rl-agents-jericho-framework-opens-up-exciting-natural-language-challenges/) mentioning how LSTM-DQN can be adapted to text-based games.

Code can be find here https://github.com/microsoft/tdqn

Regarding having access to the possible actions, you can request the `admissible_commands` when building the `EnvInfos` object (see [documentation](https://textworld.readthedocs.io/en/latest/textworld.html?highlight=admissible_commands#textworld.core.EnvInfos.admissible_commands)).  Also, you can check [Building a simple agent.ipynb](https://github.com/microsoft/TextWorld/blob/main/notebooks/Building%20a%20simple%20agent.ipynb), this is used in `RandomAgent`.

**Comment by Acejoy** [comment]
Thank you for the reply.
