### ISSUE TITLE
Make prompt-toolkit an optional dependency.

### ISSUE THREAD

**Issue by MarcCote** [microsoft/TextWorld#162]
Some systems (e.g. Google Colab) might have an old version of prompt-toolkit (TextWorld needs `prompt_toolkit<2.1.0,>=2.0.0`). Since that library is not essential to use TextWorld, I think it would be better to make it an optional dependency.

Related to #107  
Reported by @krispymelody in https://github.com/Microsoft/TextWorld/issues/107#issuecomment-487647282

**Comment by MarcCote** [comment]
While we are looking for a proper solution, @krispymelody you can use `pip install https://github.com/MarcCote/TextWorld/archive/fix_162.zip` which will only install the bare minimum. Since Google Colab already as some (older) libraries installed (e.g. gym, pillow, prompt-toolkit), it seems to be working fine except for visualization modules (mainly used for debugging).

**Comment by krispymelody** [comment]
@MarcCote Works perfectly now, appreciate the help!
