### ISSUE TITLE
Issues with generating `treasure hunter` challenges

### ISSUE THREAD

**Issue by bentrevett** [microsoft/TextWorld#164]
I am able to generate treasure hunter challenge maps using `tw-make tw-treasure_hunter --level x`, however when I try and use higher levels the map generation frequently (but not always) produces the following error:

```
Traceback (most recent call last):
  File "/home/ben/miniconda3/envs/pytorch10/bin/tw-make", line 191, in <module>
    game = make_game(settings=args.__dict__, options=options)
  File "/home/ben/miniconda3/envs/pytorch10/lib/python3.7/site-packages/textworld/challenges/treasure_hunter.py", line 108, in make
    return make_game(mode, options)
  File "/home/ben/miniconda3/envs/pytorch10/lib/python3.7/site-packages/textworld/challenges/treasure_hunter.py", line 211, in make_game
    world.state = chain.initial_state
AttributeError: 'NoneType' object has no attribute 'initial_state'
```

I can get the above error with with levels 7 onwards - `tw-make tw-treasure_hunter --level 7 --seed 5` produces an error, but seeds 1-4 do not.

From experimenting with a few seeds, the success rate seems to drop rapidly as the levels increase and I was not able to generate a single level 20 map, however levels 21 onward seem to generate completely fine all of the time.

**Comment by tavianator** [comment]
Thanks for this report!  For starters, I think maybe `sample_quest()` should be raising `NoSuchQuestError` like `make_quest()` does, rather than returning `None` only to explode later.

As for why chaining is failing to find any possible quests, I'm not sure.  Level 20 corresponds to the longest quest (10 steps), but with only 10 rooms, so maybe there just aren't enough things to do.

**Comment by bentrevett** [comment]
Looks like the issue is `node.length` never being long enough to pass this statement, and thus it never yields:
https://github.com/microsoft/TextWorld/blob/master/textworld/generator/chaining.py#L524

So like you said, the world isn't big enough to fit the desired amount of quest steps. 

One possible solution is to increase the number of rooms? +5 for each difficulty level?

**Comment by MarcCote** [comment]
I'm trying to find a way to guarantee it will always work. This code was written before #111 that why it was working before, i.e. we didn't check if the actual quest length was respected. Also, this challenge is broken for higher level (see #85).
