### ISSUE TITLE
RuntimeError when running play function with NeuralAgent

### ISSUE THREAD

**Issue by gari-marcos** [microsoft/TextWorld#173]
Hi,
When running the play function with the Neural Agent I find the following error, I have tried with both cuda and cpu devices but the error still continues. Thank you.

RuntimeError                              Traceback (most recent call last)
<ipython-input-9-a503ff1fd844> in <module>
----> 1 play(agent, "./games/rewardsDense_goalDetailed.ulx")

<ipython-input-2-2d6aa9afbf12> in play(agent, path, max_step, nb_episodes, verbose)
     33         nb_moves = 0
     34         while not done:
---> 35             command = agent.act(obs, score, done, infos)
     36             obs, score, done, infos = env.step(command)
     37             nb_moves += 1

<ipython-input-4-4de0c39589d5> in act(self, obs, score, done, infos)
    149 
    150         # Get our next action and value prediction.
--> 151         outputs, indexes, values = self.model(input_tensor, commands_tensor)
    152         action = infos["admissible_commands"][indexes[0]]
    153 

~/.local/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    489             result = self._slow_forward(*input, **kwargs)
    490         else:
--> 491             result = self.forward(*input, **kwargs)
    492         for hook in self._forward_hooks.values():
    493             hook_result = hook(self, input, result)

<ipython-input-4-4de0c39589d5> in forward(self, obs, commands, **kwargs)
     34         nb_cmds = commands.size(1)
     35 
---> 36         embedded = self.embedding(obs)
     37         encoder_output, encoder_hidden = self.encoder_gru(embedded)
     38         state_output, state_hidden = self.state_gru(encoder_hidden, self.state_hidden)

~/.local/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    489             result = self._slow_forward(*input, **kwargs)
    490         else:
--> 491             result = self.forward(*input, **kwargs)
    492         for hook in self._forward_hooks.values():
    493             hook_result = hook(self, input, result)

~/.local/lib/python3.6/site-packages/torch/nn/modules/sparse.py in forward(self, input)
    106         return F.embedding(
    107             input, self.weight, self.padding_idx, self.max_norm,
--> 108             self.norm_type, self.scale_grad_by_freq, self.sparse)
    109 
    110     def extra_repr(self):

~/.local/lib/python3.6/site-packages/torch/nn/functional.py in embedding(input, weight, padding_idx, max_norm, norm_type, scale_grad_by_freq, sparse)
   1074         with torch.no_grad():
   1075             torch.embedding_renorm_(weight, input, max_norm, norm_type)
-> 1076     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
   1077 
   1078 

RuntimeError: Expected object of type torch.LongTensor but found type torch.cuda.LongTensor for argument #3 'index'

**Comment by xingdi-eric-yuan** [comment]
Hi, 

> RuntimeError: Expected object of type torch.LongTensor but found type torch.cuda.LongTensor for argument #3 'index'
means you're mixing GPU tensor with CPU tensor together in some operations.

**Comment by gari-marcos** [comment]
Hi,
Yes, I know that but I don't know where is happening that. I'm running the [Building a simple agent ](https://github.com/microsoft/TextWorld/blob/master/notebooks/Building%20a%20simple%20agent.ipynb )notebook without changes.

**Comment by xingdi-eric-yuan** [comment]
I see, please try adding
`self.model = self.model.cuda() if torch.cuda.is_available() else self.model`
after defining self.model (in NeuralAgent class).

**Comment by gari-marcos** [comment]
That worked, thanks!
