### ISSUE TITLE
tw-extract walkthroughs creating empty file

### ISSUE THREAD

**Issue by gari-marcos** [microsoft/TextWorld#224]
Hello, I am trying to run the tw-extract command and it is working properly with every subcommand except walkthroughs. When executing it, it is creating an empty file. I think I have everything installed properly.
Thanks in advance.

**Comment by MarcCote** [comment]
Thanks for testing this new feature! For the `walkthrough` subcommand `tw-extract` looks at the game's metadata (i.e. `game.metadata["walkthrough"]`). It might be that the games you have don't have any walkthrough saved in their metadata (e.g. older games). How were the games generated?

**Comment by MarcCote** [comment]
@gari-marcos when you have a chance, can you try if the proposed fix (#225) works for your game.

**Comment by gari-marcos** [comment]
Thanks for your reply! I am using the games provided in the ```notebooks``` folder and some others I had from previous works. I created a new game with the ```tw-make``` command and I executed the ```tw-extract walkthroughs``` command, which worked properly.
Thank you so much!

**Comment by MarcCote** [comment]
I should update those games. Thanks for the info.

**Comment by MarcCote** [comment]
FYI I just updated the notebook games.
