### ISSUE TITLE
OSError: [Errno 86] Bad CPU type in executable: macOS Catalina

### ISSUE THREAD

**Issue by ayushjain94** [microsoft/TextWorld#230]
While creating a game using "tw-make custom --world-size 5 --nb-objects 10 --quest-length 5 --seed 1234 --output tw_games/custom_game.ulx", i am getting some bad cpu type executable error. While googling about this i found that macOS Catalina dropped support for 32-bit executables but i don't have any idea how to fix this. 

<img width="841" alt="Screen Shot 2020-04-07 at 1 51 51 AM" src="https://user-images.githubusercontent.com/25243968/78634983-2ecd4c80-7873-11ea-84e8-e6a2cc8243e8.png">

**Comment by tavianator** [comment]
This is because of http://inform7.com/releases/2019/10/10/catalina.html

Just need to update the Inform7 version

**Comment by MarcCote** [comment]
It seems the "Interim" version of Inform7 is backward compatible with older MacOs version, so I'm changing `setup.sh` to download that version instead.

**Comment by MarcCote** [comment]
Hi @ayushjain94, can you install the branch `fix_230` and let us know if that works for you?
`pip install https://github.com/microsoft/TextWorld/archive/fix_230.zip`

**Comment by ayushjain94** [comment]
Hey @MarcCote It's working now. Thank you so much for your prompt response.
