### ISSUE TITLE
Issue with Jericho dependancy

### ISSUE THREAD

**Issue by cponge** [microsoft/TextWorld#233]
With jericho's latest release less than 24 hours ago (version 3.0.0), its folder structure has changed... Trying to install textworld via pip returns errors finding ".../jericho/frotz".  My workaround was to clone this repo and modify the requirements file from jericho>=2.2.0  TO  jericho==2.2.0, then install via "pip install ." from the root folder.  (Also passed --no-cache-dir, but that may not have been necessary.)    Just thought I'd bring it up as I'm assuming this will become an issue for others like me just trying out Textworld!

**Comment by MarcCote** [comment]
@cponge thanks for reporting this.
@mhauskn it seems last Jericho's release on pypi misses the frotz source files.
![image](https://user-images.githubusercontent.com/660004/79029961-c88f4500-7b64-11ea-9803-b66f2bedc2f9.png)

**Comment by MarcCote** [comment]
@cponge, I forgot to mention you don't need the latest release of Jericho in order to use TextWorld, so what you did is fine. If you want to use Jericho's latest release you can manually install it from Github
`pip install https://github.com/microsoft/jericho/archive/master.zip` in the meantime.

**Comment by mhauskn** [comment]
@cponge @MarcCote Thanks for the heads up, and sorry about that! 

I've pushed a patch; Jericho v 3.0.1 should fix the issue.

**Comment by cponge** [comment]
Thanks!
