### ISSUE TITLE
game created with GameMaker doesn't understand 'fridge'

### ISSUE THREAD

**Issue by gari-marcos** [microsoft/TextWorld#236]
Hello, I was trying to create a game with the GameMaker. However, when I create a container named either 'fridge' or 'refrigerator' and I record the quest for the game I get the following message: ```You can't see any such thing.``` But it actually appears on the quest:
```
-= Kitchen =-
You arrive in a kitchen. A typical kind of place. I guess you better just go and
list everything you see here.

You can make out a refrigerator. You bend down to tie your shoe. When you stand
up, you notice a stove. The stove is usual. On the stove you make out a keycard.
```
If I leave like that when I run the game to play it that element is replaced with other name such as 'Microsoft box' or 'formless chest':
```
-= Kitchen =-
You've entered a kitchen.

You can make out a safe. Hmmm... what else, what else? You make out a closed
formless chest. You can make out a stove. The stove is usual. On the stove you
can make out a cuboid passkey and an American limited edition keycard.

```
Do you know what could be causing this problem?

Thank you in advance,

**Comment by MarcCote** [comment]
Hi. Can you share your script? Also which TextWorld version are you using?

One guess would be that the name for the container (e.g., "fridge") was not provided as an argument. For instance, `M.new("c", name="fridge")` would fix the name and the text generation system (which is called when recording a quest, and compiling/saving the game) shouldn't change it.

**Comment by gari-marcos** [comment]
Yeah sure!
```
import textworld
from textworld import GameMaker
from textworld import g_rng
g_rng.set_seed(20180329)

M = GameMaker()
kitchen = M.new_room("kitchen")
living_room = M.new_room("living room")
bedroom = M.new_room("bedroom")
bathroom = M.new_room("bathroom")
backyard = M.new_room("backyard")

kitchen_living = M.connect(kitchen.east, living_room.west)
living_bedroom = M.connect(living_room.north, bedroom.south)
living_bathroom = M.connect(living_room.east, bathroom.west)
living_backyard = M.connect(living_room.south, backyard.north)

M.set_player(living_room)

kitchen_living_door = M.new_door(kitchen_living, name = "wooden door")
M.add_fact("locked", kitchen_living_door)
living_bedroom_door = M.new_door(living_bedroom, name = "screen door")
M.add_fact("closed", living_bedroom_door)
living_bathroom_door = M.new_door(living_bathroom, name = "metal door")
M.add_fact("open", living_bathroom_door)
living_backyard_door = M.new_door(living_backyard, name = "door")
M.add_fact("open", living_backyard_door)

key = M.new(type = 'k', name = "key")
M.add_fact("match", key, kitchen_living_door)
couch = M.new(type = 's', name = 'couch')
table = M.new(type = 's', name = 'table')
living_room.add(table)
living_room.add(couch)
couch.add(key)


stove = M.new(type = 's', name = 'stove')
chicken = M.new(type = 'f', name = 'chicken')
refrigerator = M.new(type = 'c', name = 'refrigerator')
M.add_fact('closed', refrigerator)
kitchen.add(refrigerator)
kitchen.add(stove)
refrigerator.add(chicken)


bed = M.new(type = 's', name = 'bed')
tv = M.new(type = 's', name ='tv')
bedroom.add(bed)
bedroom.add(tv)

bath = M.new(type = 'c', name = 'bath')
M.add_fact('open', bath)
toilet = M.new(type = 'c', name = 'toilet')
M.add_fact('open', toilet)
sink = M.new(type = 's', name = 'sink')
toothbrush = M.new(type = 'o', name = 'toothbrush')
sink.add(toothbrush)
bathroom.add(bath)
bathroom.add(toilet)
bathroom.add(sink)

bbq = M.new(type = 's', name = 'bbq')
backyard.add(bbq)

M.render(interactive=True)

M.generate_distractors(10)

#quest = M.record_quest()

commands = ['take key from couch', ' unlock wooden door with key', 
			'open wooden door', 'go west', 'open refrigerator', 
			'take chicken from refrigerator', 'put chicken on stove']

quest = M.set_quest_from_commands(commands)



print( " > ".join(quest.commands))
print("\n" + quest.desc)

M.validate()
M.test()

game = M.build()
game_name = "./test_game_1"
game_file = M.compile(game_name)
```

Last time I tried with 'refrigerator' but I got the same result. When loading the commands from a list, they got processed like this:
```
take key from couch > unlock wooden door with key > open wooden door > go west > go west > go west > go west
```

**Comment by MarcCote** [comment]
I see what's wrong. One of the added distractors is a key for the refrigerator which causes a change in the name. By default, the names for the key and its matching container are picked from a predefined list specified in the grammar (.twg files). I've fixed this in #237.

I'll make a 1.3.2 release, once it is merged. If you wish, you can directly install the branch containing the fix. `pip install https://github.com/MarcCote/TextWorld/archive/fix_236.zip`

**Comment by gari-marcos** [comment]
Okay, thank you very much, I finally got it. Just a thing, is there a way to modify the quest description once it's done? I mean, in the game designed above 6 actions are necessary to complete it and in the goal description, they will all appear. Can I modify the goal to mention only the last action?
Thank you again.

**Comment by MarcCote** [comment]
Yes. This is how you can do it.
```python
options = textworld.GameOptions()
options.grammar.only_last_action = True

M = GameMaker(options)
```

**Comment by gari-marcos** [comment]
Okay, that was so helpful! thank you so much!!

**Comment by MarcCote** [comment]
My pleasure. Thanks for giving TextWorld a try :). We are open to feedback especially about the GameMaker's API which is truly a work-in-progress.

**Comment by gari-marcos** [comment]
I've been looking through the docs of GameMaker but I haven't been able to figure out if there is a way to insert intermediate rewards during the quest. Is this possible? Thank you again!

**Comment by MarcCote** [comment]
The way you would do that is by defining multiple quests.
```python
quest = M.set_quest_from_commands(commands)

# Adding a subquest.
from textworld.generator import Quest, Event
subgoal = Event(conditions={M.new_fact("open", kitchen_living_door)})
M.quests.append(Quest(win_events=[subgoal]))
```
Note the use of `Quest` and `Event` classes which allow you to define more complex quests.

**Comment by MarcCote** [comment]
Also, there's a PR about better documentation here: https://github.com/microsoft/TextWorld/pull/186/files

**Comment by gari-marcos** [comment]
Oh, I see, thank you again!

**Comment by gari-marcos** [comment]
Thank you!

**Comment by gari-marcos** [comment]
Hello, I am trying to set a custom quest description but I don't find any way. Is there any way to change the description of the quest? For instance, the last command is ```go north``` but I want the quest to be ```I need you to go to the bathroom.``` Is there any way to specify that?
Thank you!

**Comment by MarcCote** [comment]
I had time to investigate more your original issue (i.e., "Your objective is to attempt to take a trip south." instead of "Your objective is to attempt to take a trip **north**."). I fixed a bug we had in trying to find the "optimal" trajectory to solve a game, which was used to define the objective of the game when none is provided.

In your example, the optimal trajectory does indeed lead you to the bathroom by going north from the kitchen, but the bug was bringing the player back to the kitchen to satisfy a second time the subgoal #4.

I pushed the fix to the same PR, if you need it. Otherwise, it will be part of the next patch release.
