### ISSUE TITLE
Please comma-separate the inventory

### ISSUE THREAD

**Issue by bionicles** [microsoft/TextWorld#242]
The quality of the text in this game is mostly excellent, with one exception: inventory, which looks like:

`You are carrying: a stick of butter a legume a Comic Strip Calendar a cd`
`You are carrying nothing`

Can we upgrade this to have commas and a period:

`You are carrying: a stick of butter, a legume, a Comic Strip Calendar, a cd.`

might be something like `','.join(items)` + '.'

Just reads a bit better in a printout. Not a huge deal if there are bigger priorities

Super impressed with the project!

**Comment by MarcCote** [comment]
@bionicles with PR #243 you can expect output like this
```
> inventory
You are carrying: a type G key.

> take insect from locker
You take the insect from the locker.

> inventory
You are carrying: an insect and a type G key.

> drop insect
You drop the insect on the ground.

> drop type G key
You drop the type G key on the ground.

> inventory
You are carrying nothing.
```

**Comment by bionicles** [comment]
legit!
