### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'requirements-vis.txt'

### ISSUE THREAD

**Issue by zhaozj89** [microsoft/TextWorld#251]
When I installed TextWorld with `pip install textworld` on my macOS Catalina 10.15.7 using conda python 3.6, it reported the following error:

<img width="1420" alt="Screenshot 2020-11-02 at 10 03 57 AM" src="https://user-images.githubusercontent.com/34164876/97823174-1fbc5900-1cf3-11eb-8720-cf5064bfbdbd.png">

**Comment by MarcCote** [comment]
Thank you for reporting this. Somehow, I forgot to add that file in the MANIFEST.in. I'll fix it and make a new release this week.

In the meantime, this should work:
`pip install https://github.com/microsoft/TextWorld/archive/master.zip`

**Comment by zhaozj89** [comment]
Thanks for your reply.`pip install https://github.com/microsoft/TextWorld/archive/master.zip` works.
