### ISSUE TITLE
make_batch2 in textworld.gym 

### ISSUE THREAD

**Issue by Comp-Engr18** [microsoft/TextWorld#273]
I have the following code to train the agent, which uses make_batch2. But I have come up with error:
      module 'textworld.gym' has no attribute make_batch2
      But now the textworld.gym does not have make_batch2. I have checked [Textworld.doc](https://textworld.readthedocs.io/en/stable/textworld.gym.html) but I haven't found the make_batch2 module there.
      Can anyone tell me the alternative code to do the same task as below:
        
        env_id = make_batch2(env_ids, parallel=True)
        env = gym.make(env_id)
        env.seed(episode_no)

        obs, infos = env.reset()
        batch_size = len(obs)

**Comment by MarcCote** [comment]
Hi @Comp-Engr18,

`make_batch2` was a temporary patch to reduce the overhead associated with registering a game (via `textworld.gym.register_game(...)`). That overhead is not an issue with more recent versions of TextWorld. This means you can safely use:
```
import textworld.gym

# env_id = make_batch2(env_ids, parallel=True) 
env_id = textworld.gym.register_games(gamefiles, request_infos, batch_size, asynchronus=True)
env = gym.make(env_id)
```
**Note** that `parallel=True` has been replaced with `asynchronous=True` (the default).

Let us know if you have any followup questions.
