### ISSUE TITLE
Optional and repeatable quest

### ISSUE THREAD

**Issue by lanhoang712** [microsoft/TextWorld#287]
Hello, I am wondering if there is a function or a flag to make a quest repeatable (same rewards given when the conditions are met) and optional (doesn’t need to be completed to complete the game)?

**Comment by MarcCote** [comment]
Unfortunately, repeatable quests are not supported (yet). That would be a nice feature to add.

Regarding having optional quests, that's possible. `Quest` objects can have multiple winning events. The quest is considered completed when [any of the winning events is true](https://github.com/microsoft/TextWorld/blob/master/textworld/generator/game.py#L247-L249).

In order to help you more, I'd need to know how are you generating the quests? Is it through the GameMaker API or are you directly using `tw-make custom`?

**Comment by lanhoang712** [comment]
Thank you Mark, I am using the GameMaker API. 

The tricky thing with the optional quest is that we try to represent penalised quests that will give a negative reward - the current setup of TextWorld allows negative rewards. However if we use the Quest function, the game will expect that to be executed before the game could end. 

Your suggestion will work if we are allowed a dictionary of reward i.e. {Event_1: reward_1; Event_2: reward_2}. Alternatively is there a way to define this directly in the Game?

**Comment by MarcCote** [comment]
I managed to add support for optional and repeatable quests to TextWorld (see PR #288).

Here's the script (named `optional_quests.py`) that I'm testing it with.
```python
import argparse
from typing import Optional, Mapping

import textworld
from textworld import GameOptions
from textworld.generator import Quest, Event
from textworld.challenges import register

def make(settings: Mapping[str, str], options: Optional[GameOptions] = None) -> textworld.Game:
    M = textworld.GameMaker(options)
    museum = M.new_room("Museum")

    weak_statue = M.new(type="o", name="ivory statue")
    normal_statue = M.new(type="o", name="stone statue")
    strong_statue = M.new(type="o", name="granite statue")

    museum.add(weak_statue)
    museum.add(normal_statue)
    museum.add(strong_statue)

    M.set_player(museum)

    M.quests = [
        Quest(
            win_events=[
                Event(conditions=[M.new_fact('in', weak_statue, M.inventory)]),
            ],
            reward=-10,
            optional=True,
            repeatable=True
        ),
        Quest(
            win_events=[
                Event(conditions=[M.new_fact('in', normal_statue, M.inventory)]),
            ],
            reward=3,
            optional=True
        ),
        Quest(
            win_events=[
                Event(conditions=[M.new_fact('in', strong_statue, M.inventory)]),
            ],
            reward=5,
        )
    ]

    game = M.build()
    return game


def build_argparser(parser=None):
    parser = parser or argparse.ArgumentParser()

    group = parser.add_argument_group('Specific Game settings')

    return parser

register(name="tw-optional-quest",
         desc=("Generate games that have optional quests in them."),
         make=make,
         add_arguments=build_argparser)

```
and the commands to run:
> tw-make --third-party optional_quests.py tw-optional-quest --output games/tw-game.z8 -v -f
> tw-play games/tw-game.z8

You can try taking (or not) the stone or ivory statue before taking the granite one (which will the game). Also, note that for every step you have the ivory status in your inventory you get "rewarded" -10 points (this is the repeatable aspect).

**Comment by lanhoang712** [comment]
Wow, thank you so much @MarcCote  - you are amazing and this is exactly what we need!

**Comment by MarcCote** [comment]
Quick update. I've finalized the PR and I'll make a minor release when all the tests have passed.

**Comment by MarcCote** [comment]
TextWorld 1.5.0 has optional and repeatable quests. Please update your TextWorld installation. Thanks again for this suggestion.
