### ISSUE TITLE
Can Textworld support multiple players?

### ISSUE THREAD

**Issue by jaskonyaolei** [microsoft/TextWorld#297]
Hi, I was wondering how the project could be modified to add more players? Are there any specific renovation proposals?

**Comment by MarcCote** [comment]
Hi! Some engineering would be needed but I believe that can be done to some extent for turn-based multiplayer (i.e., each player make one/many actions then yields control to the next players).

Code changed would be needed at the Inform7 level for integrating the notion of multiple playable characters. Some starting point would be look into Inform7's documentation. For instance, to switch between players: http://inform7.com/book/WI_8_9.html

**Comment by MarcCote** [comment]
I'm closing this issue as there's no roadmap to support multiple players in TextWorld.
