### ISSUE TITLE
[Gym] - Depreciation Warning ("rewrite env with new step API")

### ISSUE THREAD

**Issue by ai-nikolai** [microsoft/TextWorld#322]
When running a simple game using Textworld + Gym, the follow depreciation warning occurs: (when typing `help`)
```bash
python3.9/site-packages/gym/utils/passive_env_checker.py:227: DeprecationWarning: WARN: Core environment is written in old step API which returns one bool instead of two. It is recommended to rewrite the environment with new step API. 
```

_Software Versions:_
1. textworld==1.5.4
2. numpy==1.26.2
3. gym==0.25.2
4. gym-notices==0.0.8

@MarcCote

**Comment by MarcCote** [comment]
Dropping `gym` dependency.
Fixed by #341
