### ISSUE TITLE
install textworld problems

### ISSUE THREAD

**Issue by yanxue7** [microsoft/TextWorld#346]
i run pip install on a Ubuntu machine , and meet the error of

        File "/mnt/nasdata/yongcheng/Anaconda/anaconda3/envs/proxy/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['./setup.sh']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for textworld
Failed to build textworld
ERROR: Could not build wheels for textworld, which is required to install pyproject.toml-based projects

**Comment by MarcCote** [comment]
Hi @yanxue7, do you have the complete log for the error message. We don't see the actual error. Also, try running

    pip install -vvv textworld

**Comment by yanxue7** [comment]
hi, I have fixed this bug, I think the conda environment with too many conflicted repos installed causes it, i rebuilt a new conda, it has been solved.
