### ISSUE TITLE
'module textworld has no attribute render'

### ISSUE THREAD

**Issue by christopherzc** [microsoft/TextWorld#352]
Hello,

I am trying to run the "Handcrafting a game.ipynb" notebook in colab, however I run into the error 'module 'textworld' has no attribute 'render'' at the third cell.

**Comment by MarcCote** [comment]
Hi @christopherzc, I just want to make sure, did you install the visualization dependencies? (see https://github.com/microsoft/TextWorld?tab=readme-ov-file#visualization)

    pip install textworld[vis]

**Comment by MarcCote** [comment]
My bad, it seems a typo sneaked in 10 months ago. Thanks!
