### ISSUE TITLE
Broken functions in text_utils

### ISSUE THREAD

**Issue by tshrjn** [Microsoft/TextWorld#71]
This [commit](https://github.com/Microsoft/TextWorld/commit/6e9d2616d0f67939abca0d65c52df12aaf0699da#diff-eb882a60fce6eaedd1f8fe4c2cad2836) last week, which removes the global constants to form a single knowledgebase, also removed a few function being used in other places. 

For instance, I found that the `extract_vocab` function in [text_utils.py](https://github.com/Microsoft/TextWorld/blob/5605863b613a041e966c82b63593e2146f0e8820/textworld/text_utils.py#L121) requires `data.get_data_path` function from the [textworld.generator.data](https://github.com/Microsoft/TextWorld/blob/master/textworld/generator/data/__init__.py) module.

This obviously makes it fail the [test_extract_vocab.py]() and possibly affect few other. This does affect the generation of [challenges/treasure_hunter.py](https://github.com/Microsoft/TextWorld/blob/404521a84b12971a68f0540244ca2bff4d5777d3/textworld/challenges/treasure_hunter.py#L185)

I temporarily fixed it for my use case by assigning `DATA_PATH = os.path.dirname(__file__)` and using it instead of `data.get_data_path()` in the `extract_vocab`.

**Comment by MarcCote** [comment]
Thank you for reporting this issue. PR #73 should address it. Let us know if that works for you.

**Comment by tshrjn** [comment]
@MarcCote Thanks for the quick response and update. And yes, it works for me now!
