### ISSUE TITLE
Problems running the notebooks

### ISSUE THREAD

**Issue by ronentk** [Microsoft/TextWorld#8]
Hi,
Exciting work with the TextWorld environment.
I was trying to run your notebooks at https://github.com/Microsoft/TextWorld/blob/master/notebooks/
but they weren't working for me properly (Ubuntu 18.04, Anaconda 5.2 with Python 3.7).

1. `M.render()` wasn't working:
To fix it, I had to:
- Install a few extra packages which weren't in the requirements file: `selenium, pybars3, flask, Pillow, gevent`
- Add to the `render/__init__.py` file: `from textworld.render.serve import get_html_template` (just a quick hack, there's probably a better way to get the imports working properly)
- Add the `chromedriver` executable from http://chromedriver.chromium.org/getting-started to the PATH
2. `notebooks/make_example_game.py` wasn't working either, to fix it I added to the `envs/__init__.py` file: `from textworld.envs.wrappers import *` (again, maybe there's a better way)

**Comment by tavianator** [comment]
#9 adds some clarifications to the README

**Comment by ronentk** [comment]
Unfortunately I don't have the error message currently, but IIRC the error was in the line `M.render()`, that the serve.py module was needed but wasn't imported.
